namespace ERService.MSSQLDataAccess.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class AddedAddressIdAutoGenerated : DbMigration
    {
        public override void Up()
        {
            AlterColumn("dbo.CustomerAddress", "Id", c => c.Guid(nullable: false, identity: true, defaultValueSql: "newsequentialid()"));
        }
        
        public override void Down()
        {
        }
    }
}
